name: Docker Image CI

on:
  workflow_dispatch:  # Это позволяет запускать workflow вручную
    inputs:
      host:
        description: 'Remote server host (e.g., user@example.com)'
        required: true
      ssh_key:
        description: 'SSH private key for deployment'
        required: true
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag iate-website:1.0.0
    - name: seave docker as .tar
      run: docker save -o iate-website.tar iate-website:1.0.0

    - uses: up9cloud/action-rsync@master
      env:
        HOST: ${{ github.event.inputs.host || secrets.HOST }}
        KEY: ${{ github.event.inputs.ssh_key || secrets.DEPLOY_SSH_KEY }}
        TARGET: iate-website.tar



