name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main # Set a branch to deploy when pushed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: updata
        run: sudo apt update && sudo apt upgrade

      - name: Install
        run: npm install

      - name: Run Typecheck
        run: npm run typecheck
